#! /bin/sh
### BEGIN INIT INFO
# Provides: dashboard
# Default-Start:     2 3 4 5
# Default-Stop:      
# Required-Start:
# Required-Stop: 
### END INIT INFO

set -e
# /etc/init.d/dashboard

NAME="Dashboard daemon"
RUBY=$(which ruby)
SERVER="/home/sysadmin/Dropbox/Repository/dashboard/server/publisher.rb"
DAEMON="$RUBY $SERVER"
CONFIG_FILE="/etc/default/dashboard"

test -x $RUBY || exit 0

. /lib/lsb/init-functions

if [ ! -s "$CONFIG_FILE" ]; then
  log_failure_msg "missing or empty config file $CONFIG_FILE"
  log_end_msg 1
  exit 0
else
  . $CONFIG_FILE
fi


dashboard_start() {
  if start-stop-daemon --start --quiet --background \
          --pidfile $PID_FILE --make-pidfile \
          --exec $DAEMON -- $DASHBOARD_OPTS
  then
    rc=0
    sleep 1
    if ! kill -0 $(cat $PID_FILE) >/dev/null 2>&1; then
      log_failure_msg "dashboard daemon failed to start"
      rc=1
    fi
  else
    rc=1
  fi

  if [ $rc -eq 0 ]; then
    log_end_msg 0
  else
    log_end_msg 1
    rm -f $PID_FILE
  fi

} #dashboard_start

case "$1" in
  start)
    if "$DASHBOARD_ENABLE"; then
      if [ -s "$PID_FILE" ] && kill -0 $(cat $PID_FILE) >/dev/null 2>&1; then
        log_end_msg 0
        exit 0
      fi
      dashboard_start
    else
      if [ -s "$CONFIG_FILE" ]; then
        log_warning_msg "$NAME not enabled in $CONFIG_FILE, not starting..."
      fi
    fi
  ;;
  
  stop)
    log_daemon_msg "Stopping $NAME"
    start-stop-daemon --stop --pidfile $PID_FILE
    log_end_msg $?
    rm -f $PID_FILE
  ;;

  restart)
    if $DASHBOARD_ENABLE; then
      log_daemon_msg "Restarting $NAME"
      if [ -s "$PID_FILE" ] && kill -0 $(cat $PID_FILE) >/dev/null 2>&1; then
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 1
      else
        log_warning_msg "$NAME not running, attempting to start"
        rm -f $PID_FILE
      fi
      dashboard_start
    else
      if [ -s "$CONFIG_FILE" ]; then
        log_warning_msg "$NAME not enabled in $CONFIG_FILE, not starting..."
      fi
    fi
  ;;

  status)
    status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
    exit $?
  ;;

esac

exit 0
